### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by neon5d** [rymc/n2d#1]
Hello, Can you provide an example of how to train N2D network?

**Comment by rymc** [comment]
Do you want to train on new data?

**Comment by neon5d** [comment]
Yes and also would like to know how to train n2d.
Thank you.

**Comment by rymc** [comment]
If you want to train then have a look at the run.sh script. For example, here is the line from the script that uses the pretrained weights.

`python n2d.py mnist 0 --ae_weights=mnist-1000-ae_weights.h5  --umap_dim=10 --umap_neighbors=20 --manifold_learner=UMAP  --save_dir=mnist-umap-n2d --umap_min_dist=0.00 `

If you want to train the weights yourself remove the --ae_weights argument and a new autoencoder will be trained, i.e. 

`python n2d.py mnist 0 --umap_dim=10 --umap_neighbors=20 --manifold_learner=UMAP  --save_dir=mnist-umap-n2d --umap_min_dist=0.00 `

Before doing this please update n2d to the latest version (with a git pull) as I just updated the code to perform better when using the CPU to train the network. The latest version will perform just as well training with the CPU as with a GPU (as I hadn't previously trained with a CPU and didn't spot a CPU-only specific bug).

If you want to use a new dataset I suggest looking at datasets.py and adding a function to load and return the x and y of your data. Note: y is only used for evaluation, so if you don't have y (the labels) then you can return None.

You will also need to slightly modify n2d to call your new data loading function. If you encounter any problems let me know.

**Comment by neon5d** [comment]
I got it. Thank you.
