### ISSUE TITLE
I cannot reproduce results when retraining

### ISSUE THREAD

**Issue by ftamburin** [rymc/n2d#10]
I am trying to reproduce the same results in the paper with the mnist dataset retraining the model from scratch. These are the parameters and the output:

Using GPU

Missing MulticoreTSNE package.. Only important if evaluating other manifold learners.

Namespace(ae_weights=None, batch_size=256, cluster='GMM', dataset='mnist', eval_all=False, gpu='0', manifold_learner='UMAP', n_clusters=10, pretrain_epochs=1000, save_dir='MYEXPS', umap_dim=10, umap_metric='euclidean', umap_min_dist='0.00', umap_neighbors=20, visualize=False)

Time to train the autoencoder: 1251.820315361023

=======================================

mnist | UMAP on autoencoded embedding with GMM - N2D
ACC 0.83611
NMI 0.8986
ARI 0.82823

============================================

They are well below the one in the paper (that I can reproduce using the provided weights):
ACC 0.979
MNI 0.942

Could you help me? Did I make some mistake?
Thanks

**Comment by rymc** [comment]
You probably didn't make a mistake. There has been a few issues raised before about similar issues but they're typically resolved for one reason or another.

My advice is to try a clean environment and retrain..

**Comment by ftamburin** [comment]
Actually I solved the problem putting umap_neighbors=10 (and not 20 as in the paper)

====================================================================

mnist | UMAP on autoencoded embedding with GMM - N2D

ACC 0.97797

NMI 0.94033

ARI 0.95197

======================================================

**Comment by rymc** [comment]
Great! I'm glad to hear it! :)
