### ISSUE TITLE
Meaning of the plots

### ISSUE THREAD

**Issue by thehappy1** [rymc/n2d#16]
Hello,
I successfully applied this technique on my own dataset and its producing really good results. Thanks for that! 
But i have one question. What is the difference betwenn the two plots called "n2d-predicted.png" and "n2d.png"?

**Comment by rymc** [comment]
You can see the difference here [1]. n2d.png is the plot with the ground truth clusters while n2d-predicted.png is the plot with the predicted clusters.


[1] https://github.com/rymc/n2d/blob/6c359365601f4389d1d23a28f1f43619187a4ece/n2d.py#L248

**Comment by thehappy1** [comment]
All right, thank you very much for that.
