### ISSUE TITLE
Choice of architecture/relation to t-sne 

### ISSUE THREAD

**Issue by josephsdavid** [rymc/n2d#9]
Hi Ryan, when you get the chance do you think you could walk through the choice of the [500, 500, 2000, c] architecture, especially with relation to t-sne (as mentioned in the paper)? I’ve been trying to understand it so I can confidently explain it to my advisor, but coming up pretty short :)

Best,

David

**Comment by rymc** [comment]
Hi David,

If you are asking about the [500 500 2000] parameters, I think that it originates from this paper: https://www.cs.toronto.edu/~hinton/absps/fastnc.pdf

**Comment by josephsdavid** [comment]
Thank you, this is exactly what I was looking for!
